apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
  labels:
    app: n8n
data:
  # Basic n8n configuration
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "admin"
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  NODE_ENV: "production"
  
  # Database configuration (SQLite for development)
  DB_TYPE: "sqlite"
  DB_SQLITE_DATABASE: "/home/n8n/.n8n/database.sqlite"
  
  # Workflow settings
  WORKFLOWS_DEFAULT_NAME: "My Workflow"
  N8N_DEFAULT_BINARY_DATA_MODE: "filesystem"
  
  # Security settings
  N8N_SECURE_COOKIE: "false"
  N8N_METRICS: "false"
  
  # Logging
  N8N_LOG_LEVEL: "info"
  N8N_LOG_OUTPUT: "console"
