apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-basic-auth
  namespace: n8n
type: Opaque
stringData:
  N8N_BASIC_AUTH_USER: admin
  N8N_BASIC_AUTH_PASSWORD: admin123  # cámbialo
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-encryption
  namespace: n8n
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: "replace-with-32+char-random-key-xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5678
          env:
            # Básicos para local/minikube
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "http"
            - name: N8N_HOST
              value: "localhost"   # no crítico en Minikube; puedes poner tu IP si quieres
            - name: WEBHOOK_URL
              value: "http://localhost:5678/"
            - name: GENERIC_TIMEZONE
              value: "America/Bogota"

            # Habilita auth básica
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-basic-auth
                  key: N8N_BASIC_AUTH_USER
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-basic-auth
                  key: N8N_BASIC_AUTH_PASSWORD

            # Cifra credenciales internas de n8n
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-encryption
                  key: N8N_ENCRYPTION_KEY

            # (Opcional) Desactiva nuevas versiones automáticas en UI
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"

          volumeMounts:
            - name: n8n-storage
              mountPath: /home/node/.n8n
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: n8n-storage
          persistentVolumeClaim:
            claimName: n8n-data
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: n8n
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
    - name: http
      port: 5678
      targetPort: 5678
      nodePort: 30679  # puedes cambiarlo si ya está usado